$:
  vscode:
    - services:
        - vscode
        - docker
      docker:
        image: docker.cnb.cool/arsrna/dev-image/nodejs
        volumes:
          - /root/.bun/install/cache
          - /root/.npm
      imports:
        - https://cnb.cool/arsrna/env/-/blob/main/npm.yml
      runner:
        cpus: 16
      stages:
        - name: 配置wakatime
          imports:
            - https://cnb.cool/arsrna/env/-/blob/main/vscode.yml
          script:
            - echo "[settings]\n" > /root/.wakatime.cfg
            - echo "api_key = ${WAKA_APIKEY}"  >> /root/.wakatime.cfg
        - name: 安装插件
          script: code-server --install-extension yzhang.markdown-all-in-one
        - name: 安装依赖
          script: bun i

  push:
    同步到gay湖北:
      stages:
        - name: sync
          image: tencentcom/git-sync
          imports:
            - https://cnb.cool/arsrna/env/-/blob/main/git.yaml
          settings:
            target_url: https://github.com/ArSrNa/react-timeline.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_email: "root@arsrna.cn"
            force: true
    单测:
      docker:
        image: docker.cnb.cool/arsrna/dev-image/nodejs
        volumes:
          - /root/.bun/install/cache
          - /root/.npm
      runner:
        cpus: 16
      stages:
        - name: 构建
          script:
            - bun i
            - bun run build
        - name: 测
          script: bun test --coverage
        - name: coverage
          type: testing:coverage
          options:
            diffLines: 78 # 增量覆盖率红线
          exports:
            lines: LINES
            diff_pct: DIFF_LINES
        - name: result
          script: echo echo "LINES $LINES DIFF_LINES $DIFF_LINES"

  # tag push 时触发
  tag_push:
    - docker:
        image: docker.cnb.cool/arsrna/dev-image/nodejs
        volumes:
          - /root/.bun/install/cache
          - /root/.npm
      runner:
        cpus: 16
      stages:
        - name: 构建部署
          script:
            - bun i
            - bun run build
            - echo $CNB_BRANCH
        - name: update version
          # 修改 package.json 中的version为当前tag，但不会提交代码
          script: npm version $CNB_BRANCH --no-git-tag-version
        - name: npm publish
          imports:
            - https://cnb.cool/arsrna/env/-/blob/main/npm.yml
          script:
            - npm publish

        - name: cnb-npm publish
          image: tencentcom/npm
          settings:
            username: $CNB_TOKEN_USER_NAME
            token: $CNB_TOKEN
            email: $CNB_COMMITTER_EMAIL
            registry: https://npm.cnb.cool/arsrna/os-npm/-/packages/
            folder: ./
            fail_on_version_conflict: false
